apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/marco-samori/ML_Bank
    targetRevision: main
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: user-marcosamori
  syncPolicy:
    automated:
      selfHeal: true
