apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/davidserruya/ML_Bank_gitops.git
    targetRevision: main
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: user-ppeltier75
  syncPolicy:
    automated:
      selfHeal: true